version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/
    
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t redcanary/cb-event-forwarder .

#      - run:
#          name: 'Run unit tests'
#          command: |
#            mkdir -p $TEST_RESULTS
#            go get github.com/jstemmer/go-junit-report
#            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
#            make test | tee ${TEST_RESULTS}/go-test.out
#
#      - store_test_results:
#          path: /tmp/test-results

      - deploy: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker push redcanary/cb-event-forwarder
          fi
