version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git

    working_directory: ~/

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build docker container'
          command: docker build -t redcanary/cb-event-forwarder .

      - deploy:
          name: Deploy latest to docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push redcanary/cb-event-forwarder
            fi
