version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce-git
    steps:
      - checkout

      - setup_remote_docker:
          version: 17.07.0-ce

      - run:
          name: Build application Docker image
          command: |
            docker --version
            docker build -t redcanary/cb-event-forwarder .

      - deploy:
          name: Deploy latest to docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push redcanary/cb-event-forwarder
            fi
