version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
        environment:
          GOROOT: ""
          PATH: "/usr/local/go/bin:/usr/local/go_workspace/bin:~/.go_workspace/bin:${PATH}"
          GOPATH: "${HOME}/.go_workspace:/usr/local/go_workspace:${HOME}/.go_project"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout
      - run:
          name: 'Build docker container'
          command: docker build -t redcanary/cb-event-forwarder .

#      - run:
#          name: 'Run unit tests'
#          command: |
#            mkdir -p $TEST_RESULTS
#            go get github.com/jstemmer/go-junit-report
#            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
#            make test | tee ${TEST_RESULTS}/go-test.out

      - store_test_results:
          path: /tmp/test-results

      - deploy:
          name: Deploy latest to docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push redcanary/cb-event-forwarder
            fi
